//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EContactBook.DataAccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=tcp:m45afjam4t.database.windows.net,1433;Database=DbEContactBook;User ID=remoteacc@m45afjam4t;Password=1qazxsw@;Trusted_Connection=False;Encrypt=True;")]
        public string DbEContactBookConnectionString {
            get {
                return ((string)(this["DbEContactBookConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=tcp:m45afjam4t.database.windows.net,1433;Database=DbEContactBook;User ID=remoteacc@m45afjam4t;Password=1qazxsw@;Trusted_Connection=False;Encrypt=True;")]
        public string DbEContactBookConnectionString1 {
            get {
                return ((string)(this["DbEContactBookConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=tcp:m45afjam4t.database.windows.net,1433;Database=DbEContactBook;User ID=r" +
            "emoteacc@m45afjam4t;Password=1qazxsw@;Trusted_Connection=False;Encrypt=True;")]
        public string DbEContactBookConnectionString2 {
            get {
                return ((string)(this["DbEContactBookConnectionString2"]));
            }
        }
    }
}
